### ISSUE TITLE
cannot import name 'IncapSession'

### ISSUE THREAD

**Issue by andycui66** [ziplokk1/incapsula-cracker-py3#10]
I am having trouble using this package. I did run `pip install incapsula-cracker-py3`.

Then I got error:
`Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/Projects/PyCharmProjects/untitled/blueMonitor.py", line 1, in <module>
    from incapsula import IncapSession
ImportError: cannot import name 'IncapSession'`

Can you please advise what else I need to do other than `pip install`?

**Comment by Amurmurmur** [comment]
@andy135790 
install required libraries listed in requirements.txt
```
beautifulsoup4==4.6.0
bs4==0.0.1
requests==2.14.2
six==1.10.0
```

Most likely you dont have six installed or all of them, just run the following for each package.
```
sudo easy_install packagename
```
