### ISSUE TITLE
Cracker does not work for any site

### ISSUE THREAD

**Issue by Felipeandradee** [ziplokk1/incapsula-cracker-py3#3]
Cracker has stopped working for **all** sites tested.

For example:
- whoscored.com
- coursehero.com
- offerup.com
- dollargeneral.com
- ioepa.com.br

**Comment by yalopov** [comment]
I got this issue too on exito.com. 

Also if it's useful to know, i wasn't doing any exhaustive scrapping on that website.

**Comment by ed-biz23** [comment]
yes cracker no longer works for me either. I tried with http://www.ubiqlife.com/

**Comment by ziplokk1** [comment]
Confirmed for whoscored.com.

I will be looking into it.

Can anyone post the error messages that they're getting?

**Comment by ziplokk1** [comment]
Please see issue #4  for follow ups with whoscored.com.

I will be looking into the other sites soon.

**Comment by ed-biz23** [comment]
this is the error I'm getting for this site http://www.ubiqlife.com/
Traceback (most recent call last):
  File "/Users/xx/Desktop/Script/beautifulsoup_tester.py", line 3, in <module>
    response = session.get('http://www.ubiqlife.com/')
  File "/Users/xx/Library/Python/3.5/lib/python/site-packages/incapsula/session.py", line 297, in get
    return self.crack(self.request('GET', url, **kwargs))
  File "/Users/xx/Library/Python/3.5/lib/python/site-packages/incapsula/session.py", line 267, in crack
    self._raise_for_recaptcha(resource)
  File "/Users/xx/Library/Python/3.5/lib/python/site-packages/incapsula/session.py", line 211, in _raise_for_recaptcha
    raise RecaptchaBlocked(iframe_response, 'resource blocked by re-captcha')
incapsula.errors.RecaptchaBlocked: resource blocked by re-captcha

**Comment by gumush** [comment]
any updates on that ? 
It looks like still not working :(

**Comment by dimon222** [comment]
@gumush i think it was resolved with #8 
Works for me...

**Comment by Jacky-Chiu** [comment]
@dimon222 which site work?[http://www.whoscored.com]()?i try the code of [#8](  ) only can work the first time...
