### ISSUE TITLE
pip install in aws instance fails

### ISSUE THREAD

**Issue by andresarslanian** [ziplokk1/incapsula-cracker-py3#5]
Hi, I'm trying to use your package in an AWS EC2 instance and when I try to install with pip I receive the following:

```
Collecting incapsula-cracker-py3
  Using cached incapsula-cracker-py3-0.1.8.1.tar.gz
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from incapsula-cracker-py3)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/site-packages (from incapsula-cracker-py3)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from incapsula-cracker-py3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/site-packages (from bs4->incapsula-cracker-py3)
Installing collected packages: incapsula-cracker-py3
  Running setup.py install for incapsula-cracker-py3 ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Vuus0N/incapsula-cracker-py3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ayy7aZ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Vuus0N/incapsula-cracker-py3/setup.py", line 23, in <module>
        include_package_data=True
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 604, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 46, in run
        self.build_packages()
      File "/usr/lib64/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in build_module
        package)
      File "/usr/lib64/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Vuus0N/incapsula-cracker-py3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ayy7aZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Vuus0N/incapsula-cracker-py3/
```

I hope you could help.

Thanks!

**Comment by ziplokk1** [comment]
After a bit of searching, it seems that the problem is with the `from __future__ import unicode_literals` line in `setup.py`. 

I won't be near a computer for a few weeks to resolve the issue personally, but if you clone the repo locally, remove the offending line from `setup.py`, then run `pip install -e /path/to/incapsula-cracker-py3` then it should work. 

Cheers!
